sudo: required
dist: trusty
language: node_js
node_js:
  - "7"
  - "6"
  - "4"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gvfs-bin libgcrypt20
script:
  - yarn test
  - node index.js -y
  - node index.js -b -y
