sudo: required
dist: trusty
language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
script:
  - node index.js -y
  - node index.js -b -y
addons:
  apt:
    packages:
      - curl
      - git
      - gconf2
      - gconf-service
      - libgtk2.0-0
      - libudev1
      - libgcrypt20
      - libnotify4
      - libxtst6
      - libnss3
      - python
      - gvfs-bin
      - xdg-utils
      - libcap2
