sudo: required
dist: trusty
language: node_js
node_js:
  - "5"
  - "4"
before_install:
  - sudo apt-get -qq update
  - >
    sudo apt-get install -y curl git libgtk2.0-0 libudev1
    libgcrypt20 libnss3 python gvfs-bin
script:
  - node index.js -y
  - node index.js -b -y
