sudo: required
dist: trusty
language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gvfs-bin libgcrypt20
script:
  - node index.js -y
  - node index.js -b -y
