sudo: required
dist: trusty
language: node_js
cache: yarn
node_js:
  - "node"
  - "lts/carbon"
  - "lts/boron"
  - "lts/argon"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gvfs-bin libgcrypt20 gconf2
install:
  - yarn --frozen-lockfile --ignore-engines
script:
  - yarn test
  - node lib -y
  - node lib -b -y
